### PR TITLE
Switch to more published forks

### PR DESCRIPTION
**Pull request by pieterdd**
This clears additional crates.io publication blockers.

See also:
- https://crates.io/crates/floem-peniko (no fork exists; this publishes linebender's version cafdac9a211a0fb2fec5656bd663d1ac770bcc81)
- https://github.com/lapce/cosmic-text/pull/3 - https://crates.io/crates/floem-cosmic-text
- https://github.com/lapce/vger-rs/pull/7 - https://crates.io/crates/floem-vger

I'm willing to transfer ownership of these crates to the Lapce/Floem dev team.

### CODE REVIEW

**Comment by dzhou121** [comment]
both the vger-rs floem crate and the vger renderer sub crate are called floem_vger

**Comment by pieterdd** [comment]
Ah, good point. What's the purpose of the vger subcrate in relation to vger-rs? Does it contain code that could be moved into the main crate as `floem::vger`?

**Comment by dzhou121** [comment]
It’s meant to be there and it is the vger renderer. Maybe rename floem-vger to floem-vger-rs?

**Comment by pieterdd** [comment]
I've aliased the floem-vger crate to floem-vger-rs in vger's Cargo.toml.

**Pull request merged**
