### PR TITLE
remove opacity setting from scroll bars

### PR DESCRIPTION
**Pull request by jrmoulton**
No need for an opacity setting as peniko::Color already support opacity

### CODE REVIEW

**Comment by jrmoulton** [comment]
Optionally the default color could be created using `scroll_bar_color: Color::rgb8(0, 0, 0).with_alpha_factor(0.7)` but then it isn't all const fn but that probably doesn't really matter

**Comment by jrmoulton** [comment]
Good as is or should it change?

**Comment by dzhou121** [comment]
Sorry for looking at this so late. The opacity was there for the fade out of the scroll bar which isn't implemented yet.

**Comment by jrmoulton** [comment]
> Sorry for looking at this so late. 
No worries. 

> The opacity was there for the fade out of the scroll bar which isn't implemented yet. 

Right. But scroll does accept a color for the scroll bar and that color should be what stores the opacity settings and not an extra field. Since peniko Color already supports opacity. This way if you pass in a color with higher or lower opacity it will change how the scroll bar looks which makes sense. Is there any reason to not store the opacity in the color?

**Comment by dzhou121** [comment]
Now thinking it again, it makes sense now.

**Pull request merged**
