### PR TITLE
dont send pointer events to overlap siblings

### PR DESCRIPTION
**Pull request by jrmoulton**

### CODE REVIEW

**Comment by dzhou121** [comment]
Do you know if web allow it?

**Comment by jrmoulton** [comment]
yeah web by default will block pointer events from overlapping sibling elements. css does have a pointer-events property that will stop the element from receiving any pointer events at all
https://drafts.csswg.org/css-ui/#hit-testing

**Comment by jrmoulton** [comment]
I could make this configurable on an application/window level so that applications that don't want to check this during layout can avoid it

**Comment by jrmoulton** [comment]
https://claude.site/artifacts/33e3ae52-b07c-4a85-93ec-3e5b8d687165

example generated with claude

**Comment by dzhou121** [comment]
Got you now. 

Maybe we could make the implementation easier. In the default view event handler, if the view doesn't have any children or no children has handled the pointer event, it stops pointer event propagation in this view.

**Comment by jrmoulton** [comment]
Ah yeah that could work. I think the logic would be if the pointer event was contained in a child, and it didn't handle it, then don't send it to any of the next children. That would be a lot simpler

**Comment by jrmoulton** [comment]
Hahah yeah that's a lot simpler

**Comment by jrmoulton** [comment]
Hmmm.. actually it might not be working as I expected

**Pull request merged**
