### PR TITLE
Add reactive child to container box

### PR DESCRIPTION
**Pull request by jrmoulton**
Sorry. Probably should've opened a PR to start with

Previous conversation in #66

### CODE REVIEW

**Comment by dzhou121** [comment]
Is it only the new views not update correctly or the original view as well?

**Comment by jrmoulton** [comment]
The original view (the container_box) seems to update just fine and the layout for it and the child is correct. But for example if I have a label somewhere in the child view the text does not appear

**Comment by jrmoulton** [comment]
https://github.com/lapce/floem/assets/13090441/150ed8fb-9e95-4ea5-a458-ef27cf5641a5

When there are events that cause an update then the text appears

**Comment by dzhou121** [comment]
I think I know what the issue now. 

When calling ```child()```, they would generate state updates, and these will be before the state change of the container box. So when the child view state update dispatches, they are not with the container box yet, so nothing happens. 

There's another paper cut. Every signal will trigger a new generated View. So it's very easy to cause unwanted view changes.

So we'll need an approach similar to list, an additional closure to trigger the view update. And the view creation needs to happen in ```update````

**Comment by jrmoulton** [comment]
Ahh interesting. 
https://github.com/lapce/floem/blob/7bcd3725290765f9d69374b883a13283646daac8/src/views/list.rs#L383C5-L395C12

I'm assuming this is the bit of the code that is most relevant?

**Comment by jrmoulton** [comment]
I've moved the view creation to the update function but I'm still having the same problem except now clicking doesn't cause any updates on the child. I'm pretty lost at this point and I definitely don't understand how this works completely. 

@dzhou121

**Comment by jrmoulton** [comment]
I think 6feda1f isn't far from correct. I think children just aren't getting the correct context. When I add debug statements to the elements every function does get run to build all of the views but they just aren't showing up.

**Comment by jrmoulton** [comment]
And from my debug statements it doesn't look like the view is being rebuilt on every signal change in the view. Only the one that should cause the view to change so it looks that that 6feda1f does have the correct behavior in response to signal changes

**Comment by jrmoulton** [comment]
Is there any way that the saving / restoring of layout and paint contexts gets messed up or doesn't account for views being built out of order because they are getting built reactively @dzhou121 ?

**Comment by jrmoulton** [comment]
🎉 🎉 🎉

**Pull request merged**
