### PR TITLE
Fix tooltip behaviour

### PR DESCRIPTION
**Pull request by Narref95**
fix https://github.com/lapce/floem/issues/413

As keyboard_navigatable only works when element is focused I cant use it to remove the tooltip, so I added the tooltip to the new WindowHandle field instead of overlays map (to be able to remove it directly).

New tooltip behaviour:
Hide tooltip when some key is pressed
Hide tooltip when PointerUp / PointerDown

### CODE REVIEW

**Review by MinusGix — APPROVED** [review]

**Comment by Long0x0** [comment]
The tooltip still shows when dragging something over:



Could you also fix this?

**Comment by Narref95** [comment]
> The tooltip still shows when dragging something over:
> 
> Could you also fix this?

Nice catch! I didn't though about dragging over the tooltip. I will try to fix that too.

**Comment by jrmoulton** [comment]
My thoughts copy/paste from discord. 

> I don't think there is a strong need to special case tooltips from overlays. 
    To me it looks like a lot of duplicated API just so that you can ensure that there is only one tooltip showing at a time. I think a better solution would be to have the events that deactivate the tooltip be better handled. 

> Part of that would be having a ClickedOutside and (probably) KeyEventOutide events

> I guess specifically in this case what is happening is that the PointerLeave event doesn't fire because the underlying view can be swapped out with keyboard events. Maybe we need to send PointerLeave if that happens

**Comment by Narref95** [comment]
> My thoughts copy/paste from discord.
> 
> > I don't think there is a strong need to special case tooltips from overlays.
> > To me it looks like a lot of duplicated API just so that you can ensure that there is only one tooltip showing at a time. I think a better solution would be to have the events that deactivate the tooltip be better handled.
> 
> > Part of that would be having a ClickedOutside and (probably) KeyEventOutide events
> 
> > I guess specifically in this case what is happening is that the PointerLeave event doesn't fire because the underlying view can be swapped out with keyboard events. Maybe we need to send PointerLeave if that happens

ClickedOutside would not be needed for this case as the tooltip needs to be removed when any PointerDown is performed (inside and outside), this has been fixed adding the handle of this event.
I like the idea of adding KeyEventOutside if this can be used to manage the overlay inside the tooltip view implementation and remove the duplicated code added.
KeyEventOutside should be sent to all widgets of the screen instead of the active one?

**Comment by Narref95** [comment]
Fixed tooltip showing when dragging something over it, also remove tooltip when pointer wheel is triggered.

PR set as draft to implement a better solution that reduces code duplication.

**Comment by Narref95** [comment]
- Added the possibility to listen keyboard events without being focused, this gives the ability to close the tooltip when any key is pressed.
This reduces code duplication instead of duplicating overlay logic for tooltips and adds this functionality to new use cases.

**Pull request merged**
