### PR TITLE
Add math ops to WriteSignal types

### PR DESCRIPTION
**Pull request by jrmoulton**

### CODE REVIEW

**Comment by dzhou121** [comment]
Sorry for replying to this PR so late. I feel like this will cause confusion?

**Comment by jrmoulton** [comment]
No worries. 

I put up the PR to have a place to discuss

I see a small benefit for a more concise update syntax cause honestly the update method is pretty verbose. I was reaching for ways to simplify it. 

I also see it causing potential confusion so I'm not heavily attached to this PR but I do wish the update syntax was more concise

**Comment by univerz** [comment]
btw [`<button on:click=move |_| *set_value.write() -= step>"-1"</button>`](https://discord.com/channels/1031524867910148188/1031525141382959175/1148679343451680818)

**Comment by jrmoulton** [comment]
Closing for now

**Pull request closed without merging**
