### PR TITLE
switch svg and button default to static

### PR DESCRIPTION
**Pull request by jrmoulton**

### CODE REVIEW

**Comment by jrmoulton** [comment]
I think zoxc mentioned this a while ago and now I pretty strongly agree with it

**Comment by dzhou121** [comment]
would something like this would be better

```rust
pub fn svg(svg_str: impl Into<String> + 'static) -> Svg {
    let id = ViewId::new();
    id.update_state(svg_str);
    Svg {
        id,
        svg_tree: None,
        svg_hash: None,
    }
    .class(SvgClass)
}

impl Svg {
    pub fn update(self, svg_str: impl Fn() -> String + 'static) -> Self {
        let id = self.id;
        create_effect(move |_| {
            let new_svg_str = svg_str();
            id.update_state(new_svg_str);
        });
        self
    }
}
```

so that we don't have `svg` `dyn_svg`

**Comment by jrmoulton** [comment]
ah yeah that seems good. I think update makes sense.

**Comment by jrmoulton** [comment]
used update_svg as the method to avoid confusing with View update method

**Comment by dzhou121** [comment]
maybe consider using `value` so that we can use it for all views that needed it, e.g. `label` etc

**Comment by dzhou121** [comment]
or `update_value`?

**Comment by jrmoulton** [comment]
👍

**Pull request merged**
