### PR TITLE
Transform view

### PR DESCRIPTION
**Pull request by timsueberkrueb**
Useful component for scroll views/pan zoom areas and similar applications. Not sure if we want this in floem, but I'm opening this for discussion.

### CODE REVIEW

**Comment by jrmoulton** [comment]
What is the use case for this view if you can set the translation and scale on a view using the styles?

**Comment by timsueberkrueb** [comment]
It doesn't go beyond being a convenience component for scroll/pan zoom areas. I'm also leaning towards not adding it to floem. Perhaps I can change the example to set the style directly.

**Comment by timsueberkrueb** [comment]
Or add the transform view as part of the example instead?

**Comment by timsueberkrueb** [comment]
I mostly care about having a test case/example for this application.

**Pull request closed without merging**
