### PR TITLE
deps: kurbo is used via peniko.

### PR DESCRIPTION
**Pull request by waywardmonkeys**
Since all usages of `kurbo` are via `peniko`, the direct dependency on `kurbo` is not needed. This makes it easier to keep versions in sync.

The re-export of `kurbo` was happening directly so it could have been out of sync with an updated `peniko`, so re-export the version from `peniko` instead.

### CODE REVIEW

**Comment by waywardmonkeys** [comment]
(Noticed this when looking at your branch that replicates the `vello` bug.)

**Comment by dzhou121** [comment]
peniko 0.1.0 doesn't give the options to turn on serde feature on kurbo. That's why we had to use kurbo directly.

**Comment by waywardmonkeys** [comment]
I see.

The current `main` branch of `peniko` has `serde` support now, so would it be useful if we did a release of that?

**Comment by dzhou121** [comment]
> I see.
> 
> The current `main` branch of `peniko` has `serde` support now, so would it be useful if we did a release of that?

Yes!

**Comment by waywardmonkeys** [comment]
Okay, `peniko` version 0.1.1 is published now and this PR is now updated to use it and enable the `serde` feature.

**Comment by dzhou121** [comment]
Thanks!

**Pull request merged**
