### PR TITLE
Fix close window

### PR DESCRIPTION
**Pull request by SunDoge**
Now we can close the window by clicking the close button. However, I'm not sure whether the `WindowClosed` event should be placed in the `fn destroy` or the `fn request_close`.

### CODE REVIEW

**Comment by dzhou121** [comment]
One thing I need to quickly point out is that Mac doesn't quit the app when the windows are closed.

**Comment by SunDoge** [comment]
Unfortunately, I don't have a MacOS device for testing. On Linux, `Application::global().quit()` can make the app exit after the window is closed. This code is from xilem [https://github.com/linebender/xilem/blob/main/src/app_main.rs#L169](https://github.com/linebender/xilem/blob/main/src/app_main.rs#L169). Is xilem works properly on MacOS?

**Comment by dzhou121** [comment]
I guess I can merge this first and refine it later, if you could resolve the conflict.

**Comment by SunDoge** [comment]
Done.

**Pull request merged**
