### PR TITLE
Support drawing circles

### PR DESCRIPTION
**Pull request by jrmoulton**
I wasn't sure the best way to implement this. It would make sense to support ellipses instead of circles (that would work better with both width and height properties) but this seemed to be what is currently supported in vger.

### CODE REVIEW

**Comment by dzhou121** [comment]
I'm wondering if it's probably cleaner to do the css approach, e.g., it became a circle when the border-radius is greater than 50%.

**Comment by jrmoulton** [comment]
This is what I initially tried to do but kurbo has a cap on the amount of border radius that can be set

**Comment by dzhou121** [comment]
Yeah I tried it and it didn't work. 

We can probably just create a circle "manually" with a ```if border_radis >= 50%```

**Comment by jrmoulton** [comment]
Ahh yeah that would be better. It still has the problem of not taking into account both width and height but that's at least better

**Comment by jrmoulton** [comment]
I'm starting to think that the problem is actually in vger. The rounded rectangles in kurbo are just fine. My initial guess is that the issue is here
https://github.com/lapce/vger-rs/blob/aa84d85c9f7df9da6ef47a2b6d43fe6909023b9b/src/shader.wgsl#LL106C1-L110C2

**Comment by jrmoulton** [comment]
I just updated to the macOS beta and this is no longer an issue. Border radius does actually change the border radius the way it should

**Pull request closed without merging**
