### PR TITLE
add: disable default view events

### PR DESCRIPTION
**Pull request by jrmoulton**
not a breaking change. unless code adds id.disable_default_event, no behavior of event handling will change

### CODE REVIEW

**Comment by jrmoulton** [comment]
any opposition to adding this?

**Comment by dzhou121** [comment]
What’s the use case for this?

**Comment by jrmoulton** [comment]
I have a text_input that I want to not process any events, but I don't want to mark it as disabled because that will stop it from being able to be focused using the keyboard and tab.

**Comment by jrmoulton** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/Event/preventDefault

**Pull request merged**
